print("welcome to the band name generator")
a=input("What's the name of the city you grew up in? ")
print(a)
b=input("What's your pet's name? ")
print(b)
print("Your name name could be ",a + " "+ b )